language: node_js
node_js:
- '7'
env:
  global:
    USE_CLOUD: true
    secure: KYM6v2CQoc+qXODzfn5ipPcffhujldMU2k7m4Fe3b+Yi+dbb8DT2dHhWIXpJU8E2irfuBUNrOjl9fKWmvJf9m108olpED93nkXxtiUh5cWUs7ahwED3GtdMqN1mzYIlAqnUT63u2A4N4MtBNkJlx5tj5dzZN5OWDq15XjquRZ0panXCDUS4NMOccXqxI5n3S/6JzQPXv2d3i5cd7OBY7h5Z/KngEGAavNidSKNQcUCu/k5/f6pMvMjaD1kcTMwskt1l8f153L0kH6iqEAPEb+Z/Joo9y0miwN0JXMRUrLrasob2IAYl6K/15DGpdW2QO5i+JWV12lV6P279Gjf1Eaz0GbeDrjCv93RlytA5gh9bqQVNcTTgPt4VFxHDBubBp5EWtlp0o3NB/zgz85Jt987bXl6IuXugr5Jeof8l2EyLxKnINeemcF6GKxJnQR83SSPub+lYT/za1KCmnkgaSdJPK15fmEHQOPMIeIWG/JD+ISEQCTDIjW5PxeCzJ31kpqTVEI2/SMVRNlZWuKGoXZfQhKcrhNsJiXHbjTMg8C0nU6YDQk8ASevisMi8OUqSlUV8ePSK24b203NkSCM+x2c+6qN92/ZJmCs4Yw4Q0U9rb6a6D/cCmIXoneQAixLrWb/O29YE/10Sc3W4FOPUkTdwyrdEDDR12Xt/BtFYNtk8=
