language: node_js
node_js:
- '7'
env:
  global:
    USE_CLOUD: true
    MICROSOFT_CLIENT_SECRET:
      secure: "oIHhckOQSZqQfHCADX0MBGxE6HF8Xbhp4gh7dc4WXlxX8k9w6Qq6YOXr/UDFRlYfv3B0paL8SXjb+xYosQ4y0xNiePlFu41O+oObhshXTU+kHMPN4ogYsiln6MzLJE57aLSaK9nwCH/bBx3qQDUqcvrYfAtZ+nQFyfnfPRPgHTuX2WJya2EoJQBo6/gjvVnNZuj5U+2Zyr/6NMbXHGMzO4HRhD31+wP/cAVXFjpxXQFN+tXuHE/JyXi9vTDfkVyYrNOPmswSjfbShLVGS1cEvxHjCdhDr1sAdBtWxwLn+ctjgC+P4yP8l0vnc9rCBJto+oedN3T3UMOYPJp2nlTenZ9UMhZrfqaCdk8ccIkIM+t/F5rCfCkFivBGYqPJdnBAsiu5kYG1PFxhNBH3kloiOVjf2I68/7kx35a0KSfQFza7aME3isjrfHphQTy4HibbZCTrnpLDcfMNFqW/mmPK6Y+nE4hSc9pYBd99zs/1IONBFq2Rlux6ujw42nasGJUYkhhn11hKSQLdYGQxRAgUEaxkaIMcE8RdMazPSXTYEMvvwcdVXr3NJM8sFhgjgTEkT2UmryahRY5OAKWo8dTjBAeMKaN/BOdF0mfAATH0p5PlQ9TuJXtO+oaSCIl92viC9JhJ0dxJZQElLGq/Dgb2ZbZNP2awcNK04yghmtN/xWk="
