language: node_js
node_js:
- '7'
env:
  global:
    - USE_CLOUD=true
    - secure: "b9RLqWaUSpTGmIxlGsfnCUG5Z0TH1re7XxPDGoO1My03uQFCELhw0sEXmh+Ennw7UtT6AtggV74IxZJfaU+J0qnnKyEt1hCmEMGD3eXAuj1xnoskcdzMIMzWXXtIC7Mwmlm9DGurjbC3M05s2zGuYLkRpOkJ6QlrNOmGCDzRHIgNhv8uEHwYD89+0H81Sk3USBCKZNKJo8wNLgU6bm4g+cYF1Q3C58rkhMAQBWgWinH5AhNzlGESQdseqGEWxP+YOf0J0jHesoDV0r1KrmvFaCzyTQ5D+WTTRihPCTgxjOJzhKc7+sexciQ/w+zFDFul66R7oHZORTfbi6q71PO+EqXaZoXPQ8XE6Qqp1ppRO+0E+xUCrrnKh9dx20Am9ZI09ovs0oohVhxaErekChn/VWJs5+Ui1VliVV+d9cflkOsYEsfX5zmUnDGcz228tGqOX+pFI6znxlsUcXMcEZIVimEqmgSCBe5Wke1kGFJHjBM0s/n8DY+kJVeZK2/9AVUCMHJ4eau2ZDaJujgcO3QMi+r67aQWFrNgcIuvzrvMxravEX+B3V6LoLdRvrH+SkcN2tokAksQ8TaeQr23SS63zBFvrBGNloczZVRplrVfPWF1Y5zBjI/8UaWUT72QzORxHMYm0FXe7A51kTshNAz1Z5BTjHQHDukMKgji6U01P74="
